Repository SystemJAADE/healthy-patients-service, pull requests merged in 2023-09, with the labels that each got.

#29 docs: Improve documentation
  .github/wiki/2.-Leer-antes-de-instalar.md
  .github/wiki/4.-Instalacion-manual-linux.md
  .github/wiki/5.-Instalacion-manual-windows.md
Labels: documentation

#30 chore: remove SHADOW_DB_PASS env and simplify shadow db configuration
  .env.example
  .github/wiki/5.-Instalacion-manual-windows.md
Labels: documentation, enhancement

#32 chore: Add missing binaryTargets to schema.prisma
  prisma/schema.prisma
Labels: bug

#33 chore: Remove nginx from docker layer
  .env.example
  .github/wiki/3.-Instalacion-con-docker.md
  .github/wiki/4.-Instalacion-manual-linux.md
  .github/wiki/5.-Instalacion-manual-windows.md
  .gitignore
  docker-compose.yml
  ext/nginx.conf.example
Labels: enhancement

#34 docs: Add documentation about prisma generate
  .github/wiki/5.-Instalacion-manual-windows.md
Labels: documentation

#35 chore: Remove SHADOW_DB_PASS leftover from docker
  docker-compose.yml
Labels: bug

#38 chore: Add Caddyfile
  .github/wiki/6.-Reverse-proxy.md
  Makefile
  ext/Caddyfile
Labels: documentation, enhancement

#40 chore: Add host and port in mysql healthcheck
  docker-compose.yml
Labels: bug

#42 chore: Remove make and only use yarn
  .github/wiki/2.-Leer-antes-de-instalar.md
  .github/wiki/4.-Instalacion-manual-linux.md
  .github/wiki/6.-Reverse-proxy.md
  Dockerfile
  Makefile
  bin/start-dev.sh
  bin/start-prod.sh
  package.json
Labels: enhancement

#45 chore: Fix wiki bi-directional sync
  .github/workflows/sync_docs.yml
Labels: bug

#46 docs: Add System JAADE logo
  .github/images/sj_logo.gif
  README.md
Labels: documentation

#48 feat: Create .gitatributes eol(LF)
  .gitattributes
Labels: enhancement
